export const CLEAR_ORDER_DETAILS: 'CLEAR_ORDER_DETAILS' = 'CLEAR_ORDER_DETAILS';

export const SET_ORDER_DETAILS_REQUEST: 'SET_ORDER_DETAILS_REQUEST' = 'SET_ORDER_DETAILS_REQUEST';
export const SET_ORDER_DETAILS_SUCCESS: 'SET_ORDER_DETAILS_SUCCESS' = 'SET_ORDER_DETAILS_SUCCESS';
export const SET_ORDER_DETAILS_FAILED: 'SET_ORDER_DETAILS_FAILED' = 'SET_ORDER_DETAILS_FAILED';