export const ADD_SELECTED_INGREDIENT: 'ADD_SELECTED_INGREDIENT' = 'ADD_SELECTED_INGREDIENT';
export const DELETE_SELECTED_INGREDIENT: 'DELETE_SELECTED_INGREDIENT' = 'DELETE_SELECTED_INGREDIENT';
export const MOVE_SELECTED_INGREDIENT: 'MOVE_SELECTED_INGREDIENT' = 'MOVE_SELECTED_INGREDIENT';
export const CLEAR_SELECTED_INGREDIENTS: 'CLEAR_SELECTED_INGREDIENTS' = 'CLEAR_SELECTED_INGREDIENTS';