import {
    WS_ORDERS_CONNECTION_START
    , WS_ORDERS_CONNECTION_SUCCESS
    , WS_ORDERS_CONNECTION_ERROR
    , WS_ORDERS_CONNECTION_CLOSED
    , WS_ORDERS_CONNECTION_DESTROY
    , WS_ORDERS_GET_MESSAGE
    , WS_ORDERS_SEND_MESSAGE

    , WS_ORDERS_ALL_CONNECTION_START
    , WS_ORDERS_ALL_CONNECTION_SUCCESS
    , WS_ORDERS_ALL_CONNECTION_ERROR
    , WS_ORDERS_ALL_CONNECTION_CLOSED
    , WS_ORDERS_ALL_CONNECTION_DESTROY
    , WS_ORDERS_ALL_GET_MESSAGE
    , WS_ORDERS_ALL_SEND_MESSAGE
} from "../constants";

  export type TWSStoreActions = {
    wsInit: typeof  WS_ORDERS_CONNECTION_START | typeof  WS_ORDERS_ALL_CONNECTION_START,
    wsDestroy: typeof  WS_ORDERS_CONNECTION_DESTROY | typeof  WS_ORDERS_ALL_CONNECTION_DESTROY,
    wsSendMessage: typeof  WS_ORDERS_SEND_MESSAGE | typeof  WS_ORDERS_ALL_SEND_MESSAGE,
    onOpen: typeof  WS_ORDERS_CONNECTION_SUCCESS | typeof  WS_ORDERS_ALL_CONNECTION_SUCCESS,
    onClose: typeof WS_ORDERS_CONNECTION_CLOSED | typeof  WS_ORDERS_ALL_CONNECTION_CLOSED,
    onError: typeof  WS_ORDERS_CONNECTION_ERROR | typeof  WS_ORDERS_ALL_CONNECTION_ERROR,
    onMessage: typeof  WS_ORDERS_GET_MESSAGE | typeof  WS_ORDERS_ALL_GET_MESSAGE
  };